### PR TITLE
Proposal: Rename shipyard properties

### PR DESCRIPTION
**Pull request by agrimmer**

### CODE REVIEW

**Comment by agrimmer** [comment]
Please do not merge this PR. This serves as basis for discussion for our community meeting on 2019-11-11.

**Comment by johannes-b** [comment]
I don't see any practical need of having the term `strategy` added to *deployment* and *tests*.

**Comment by dirkwall** [comment]
I agree, this would make the `shipyard` cleaner. Although this does no harm, we need to find the right point in time to make this change, as it is a breaking change.

**Comment by christian-kreuzberger-dtx** [comment]
Will be discussed after 0.6 release

**Comment by johannes-b** [comment]
I closed this proposed spec change due to a broader discussion around shipyard as shown here: https://github.com/keptn/enhancement-proposals/pull/6

**Pull request closed without merging**
