### PR TITLE
#55 added evaluation.invalidated event

### LINKED ISSUE #55: Missing Keptn CloudEvent evaluation.invalidated in 0.2.0-alpha
In 0.1.7 we still had evaluation.invalidated: https://github.com/keptn/spec/blob/0.1.7/cloudevents.md#evaluation-invalidated

This is missing in the 0.2.0-alpha spec.

We should introduce this CloudEvent again, but using our new CloudEvents spec, e.g.:

```
sh.keptn.event.invalidate-evaluation.(triggered/started/finished)
```

with a similar payload than before.

### PR DESCRIPTION
**Pull request by bacherfl**
Closes #55

### CODE REVIEW

**Comment by johannes-b** [comment]
@bacherfl the change looks good to me, but I would like to ask whether you generated it using the command: `keptn generate cloud-events-spec` ?

**Comment by bacherfl** [comment]
> @bacherfl the change looks good to me, but I would like to ask whether you generated it using the command: `keptn generate cloud-events-spec` ?

Yes, the change was generated with that command (the command has been adapted in https://github.com/keptn/keptn/pull/3271)

**Comment by johannes-b** [comment]
Perfect!

**Review by johannes-b — APPROVED** [review]
lgtm

**Pull request merged**
